openapi: 3.0.0
info:
  title: Data Whiteboard API
  description: Data Sharing Whiteboard API
  contact:
    email: mike.conway@nih.gov
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8080/angrygoat/data_whiteboard/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /objects:
    get:
      tags:
      - developers
      summary: searches user-visible objects
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      operationId: search_objects
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WhiteboardItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.developers_controller
    post:
      tags:
      - objects
      summary: adds a whiteboard item
      description: Adds an item to the system
      operationId: add_object
      requestBody:
        description: whiteboard item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WhiteboardItem'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.objects_controller
components:
  schemas:
    WhiteboardItem:
      required:
      - data_type
      - freshDate
      - guid
      - name
      - payload
      - source
      - user
      type: object
      properties:
        guid:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: My favorite compound
        data_type:
          type: string
          example: Chemical
        source:
          type: string
          example: Chemmaps
        user:
          type: string
          example: user1@nih.gov
        freshDate:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        payload:
          type: object
      example:
        payload: {}
        name: My favorite compound
        data_type: Chemical
        guid: d290f1ee-6c54-4b01-90e6-d701748f0851
        freshDate: 2016-08-29T09:12:33.001Z
        source: Chemmaps
        user: user1@nih.gov

